# Generated by Django 3.0.6 on 2020-05-20 14:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.FileField(upload_to=edu.models.image_folder)),
                ('slug', models.SlugField(max_length=25, verbose_name='Kalit so`z *')),
                ('description', models.TextField(max_length=1550, verbose_name='Kurs xaqida *')),
                ('status', models.BooleanField(default=True)),
                ('groups', models.PositiveIntegerField(blank=True, default=0)),
                ('studends', models.PositiveIntegerField(blank=True, default=0)),
                ('reg', models.DateTimeField(auto_now_add=True)),
                ('bot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Ismi')),
                ('email', models.CharField(db_index=True, max_length=55, verbose_name='Email')),
                ('message', models.CharField(max_length=1225, verbose_name='Xabar')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='auth.User')),
                ('title', models.CharField(max_length=200)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='Familyasi')),
                ('adres', models.CharField(blank=True, max_length=355, verbose_name='Manzil')),
                ('info', models.CharField(blank=True, max_length=755, verbose_name='User xaqida')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Telefon')),
                ('telegram_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Telegram ID')),
                ('limit_to', models.CharField(blank=True, max_length=30)),
                ('send_sms_date', models.CharField(blank=True, max_length=30)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('is_teacher', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('gold', models.BooleanField(default=False)),
                ('learning', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('bot', models.BooleanField(default=False)),
                ('reg', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('slug', models.SlugField(max_length=85, verbose_name='Kalit so`z *')),
                ('number', models.PositiveIntegerField(default=0)),
                ('avilable', models.BooleanField(default=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=25, verbose_name='Ismi')),
                ('password', models.CharField(blank=True, max_length=25, verbose_name='Familyasi')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
