# Generated by Django 3.0.6 on 2020-05-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='learning',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='premium',
        ),
    ]
