# Generated by Django 3.0.6 on 2020-05-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20200521_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='learning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
