# Generated by Django 3.0.6 on 2020-05-22 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_auto_20200521_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu.UserAccount'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
