# Generated by Django 3.0.6 on 2020-05-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20200522_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lock',
            field=models.BooleanField(default=True),
        ),
    ]
