# Generated by Django 3.0.6 on 2020-05-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_learn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='course',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='courses',
            field=models.ManyToManyField(to='edu.Course'),
        ),
    ]
