# Generated by Django 3.0.6 on 2020-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_auto_20200522_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cur_course',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
