# Generated by Django 3.0.6 on 2020-05-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_useraccount_cur_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='avilable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learn',
            name='ball',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
