# Generated by Django 3.0.6 on 2020-05-22 09:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_auto_20200522_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='course',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='edu.Course'),
            preserve_default=False,
        ),
    ]
