# Generated by Django 3.0.6 on 2020-05-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_learn_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.Course'),
        ),
    ]
