# Generated by Django 3.0.6 on 2020-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_auto_20200522_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
