# Generated by Django 3.0.6 on 2020-05-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_lesson_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=950)),
                ('number', models.PositiveIntegerField(blank=True, default=0)),
                ('reg_data', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=550)),
                ('is_answer', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('number', models.PositiveIntegerField(blank=True, default=0)),
                ('reg_data', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.Question')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
    ]
